markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: 2..3
plugins:
  - github-pages
remote_theme: rakutentech/android-buildconfig@gh-pages-theme

title: Mini App SDK for JS
description: Use Android/iOS device features and other extended features in mini apps.
repository: rakutentech/js-miniapps

docs_path: docs
api_docs_path: api

collections:
  versions:
    order:
      - 1.0/1.0.md
      - 1.1/1.1.md
      - 1.2/1.2.md
      - 1.3/1.3.md
      - 1.4/1.4.md
      - 1.5/1.5.md
      - 1.6/1.6.md
      - 1.7/1.7.md
      - 1.8/1.8.md
      - 1.9/1.9.md
      - 1.10/1.10.md
